modify name

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -38,14 +38,14 @@ jobs:
     - name: Attempt to build executable
       id: first-attempt
       run: |
-        pyinstaller src/allie/flowkit/__main__.py --onefile --name ${{ github.event.repository.name }}-${{ github.ref_name }} || echo "First attempt failed; adjusting recursion limit for next try."
+        pyinstaller src/allie/flowkit/__main__.py --onefile --name ${{ github.event.repository.name }}-test || echo "First attempt failed; adjusting recursion limit for next try."
       continue-on-error: true
 
     - name: Modify spec file and retry build
       if: steps.first-attempt.outcome == 'failure'
       run: |
-        echo "import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)" >> ${{ github.event.repository.name }}-${{ github.ref_name }}.spec
-        pyinstaller ${{ github.event.repository.name }}-${{ github.ref_name }}.spec
+        echo "import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)" >> ${{ github.event.repository.name }}-test.spec
+        pyinstaller ${{ github.event.repository.name }}-test.spec
 
     - name: Upload artifact
       uses: actions/upload-artifact@v4
